version: "3.7"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.0
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 32032
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    volumes:
    - ${WORKING_DIR}/zookeeper/data:/var/lib/zookeeper/data
    - ${WORKING_DIR}/zookeeper/logs:/var/lib/zookeeper/log
  kafka:
    image: confluentinc/cp-kafka:6.1.0
    network_mode: host
    environment:
      KAFKA_ZOOKEEPER_CONNECT: localhost:32032
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ${WORKING_DIR}/kafka/data:/var/lib/kafka/data

