version: "3.7"
services:
  rabbitmq:
    image: library/rabbitmq:3-management-alpine
    ports:
    - 5672:5672
    - 15672:15672
    volumes:
    - rabbit_data:/var/lib/rabbitmq/mnesia

volumes:
  rabbit_data:
