apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-template-hello-world-
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      steps:
        - - name: artifact
            template: listdir


    - name: listdir
      inputs:
        artifacts:
          - name: test_repo
            path: /src
            git:
              repo: https://github.com/yaroslav-codefresh/test.git
              revision: master
      container:
        image: alpine
        command: [sh, -c]
        args: ['ls /src']

