apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
    namespace: argo-events
  dependencies:
    - name: push
      eventSourceName: github
      eventName: push
  triggers:
    - template:
        name: wft-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflowtemplates
          # patch is apply
          operation: patch
          source:
            url:
              path: https://raw.githubusercontent.com/yaroslav-codefresh/argo/main/k8s/workflow-templates/whalesay.template.yaml
