apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
    namespace: argo-events
  dependencies:
    - name: test-dep
      eventSourceName: github
      eventName: example
  triggers:
    - template:
        name: wft-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflowtemplates
          # update also creates
          operation: update
          source:
            url:
              path: https://raw.githubusercontent.com/yaroslav-codefresh/argo/main/k8s/workflow-templates/whalesay.template.yaml
