apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      eventSourceName: github
      eventName: example
  triggers:
#    - template:
#        name: http-trigger
#        http:
#          url: http://192.168.99.1:9090/events
#          payload:
#            - src:
#                dependencyName: test-dep
#                dataKey: body
#              dest: data
#            - src:
#                dependencyName: test-dep
#                contextKey: "@this"
#              dest: context
#          method: POST
#          headers:
#            Content-Type: "application/json"
    - template:
        name: wft-trigger
        k8s:
          operation: apply
          source:
            url: https://raw.githubusercontent.com/yaroslav-codefresh/argo/tree/main/k8s/workflow-templates/whalesay.template.yaml
