apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: wft-resource
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
    namespace: argo-events
  dependencies:
    - name: workflow-template-operation
      eventSourceName: wft-resource
      eventName: workflow-templates
  triggers:
    - template:
        name: http-trigger
        http:
          url: http://local.codefresh.io/argo/api/events
          payload:
            - src:
                dependencyName: workflow-template-operation
                dataKey: body
              dest: data
            - src:
                dependencyName: workflow-template-operation
                contextKey: "@this"
              dest: context
          method: POST
          headers:
            Content-Type: "application/json"
            Authorization: "600b4b19354c1e0e06546ebf.e14f53541430b21441e3fbb60a92dedc"
          policy:
            status:
              allow:
                - 200
                - 201
