apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: workflow-resource
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
    namespace: argo-events
  dependencies:
    - name: workflow-operation
      eventSourceName: workflow-resource
      eventName: workflows
  triggers:
    - template:
        name: http-trigger
        http:
          url: http://192.168.99.1:9090/events
          payload:
            - src:
                dependencyName: workflow-operation
                dataKey: body
              dest: data
            - src:
                dependencyName: workflow-operation
                contextKey: "@this"
              dest: context
          method: POST
          headers:
            Content-Type: "application/json"
