apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: wft-resource
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa # assign a service account with `get`, `list` and `watch` permissions on the resource being watched.
  resource:
    workflow-templates:
      # namespace to listen events within
      namespace: argo
      # resource group
      group: argoproj.io
      # resource version
      version: v1alpha1
      # resource kind
      resource: workflowtemplates
      # type of events
      # possible values are ADD, DELETE, UPDATE
      # Optional
      eventTypes:
        - ADD
        - UPDATE
        - DELETE
