apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: workflow-resource
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  resource:
    workflows:
      namespace: argo
      group: argoproj.io
      version: v1alpha1
      resource: workflows
      eventTypes:
        - ADD
        - UPDATE
        - DELETE
